<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="vieworder.aspx.cs" Inherits="Admin_vieworder" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="banner">
        <h2>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
            <a href="Users.aspx">Home</a> <i class="fa fa-angle-right"></i><span>view order</span>
        </h2>
        </div>
        <br />
        
        <asp:GridView ID="grd1" runat="server" DataKeyNames="crt_id" DataSourceID="gr1" AutoGenerateDeleteButton="true"
            OnSelectedIndexChanged="grd1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="crt_id" HeaderText="cart id" />
                <asp:BoundField DataField="i_id" HeaderText="i id" />
                <asp:BoundField DataField="u_id" HeaderText=" u id " />
                <asp:BoundField DataField="quantity" HeaderText="qty" />
                <asp:BoundField DataField="status" HeaderText="status" />
            </Columns>
        </asp:GridView>
    </div>
 
    

<asp:SqlDataSource ID="gr1" runat="server" ConnectionString="<%$ ConnectionStrings:conn %>" 
        ProviderName="System.Data.SqlClient" SelectCommand="select * from [cart]" 
        DeleteCommand="delete from [cart] where crt_id=@crt_id" onselecting="s1_Selecting"> 
 </asp:SqlDataSource>

</asp:Content>

